### ISSUE TITLE
Question about `SoBelow` config in this repo

### ISSUE THREAD

**Issue by pdgonzalez872** [mirego/elixir-boilerplate#102]
Hi! Thanks for making this open source! This is an amazing resource for the community!

I have a question about `SoBelow` errors/best practices:

I see that you ignore
`Config.HTTPS` (https://github.com/mirego/elixir-boilerplate/blob/master/.sobelow-conf#L8)
This is interesting because I've seen this be triggered even when there is no
http connection whatsoever, so it makes sense that you ignored it.

My question has to do with the `Config.CSP` check that you don't ignore and actually solve.
In a fresh `phx.new` app, `sobelow` cries because it doesn't find the map in
`plug :put_secure_browser_headers` in `router.ex`

I actually wanted to learn more about this issue. So I created this:
https://github.com/nccgroup/sobelow/issues/61 which eventually led to a patch
on their docs here: https://github.com/nccgroup/sobelow/pull/62

Then, I stumbled upon how you solve the problem:
https://github.com/mirego/elixir-boilerplate/blob/master/lib/elixir_boilerplate_web/content_security_policy.ex#L1

I was wondering if there is anything we can do. Maybe we:
- make this solution more visible (maybe another patch to sobelow?)
- push this to phoenix? and have this be a default of sorts? I'm very
  cautions with security related code and love when there are standards that we
  just follow and trust. Since `sobelow` itself is somewhat new, maybe this is
  just a natural progression we are experiencing.
- add this to Phoenix's docs somewhere?

Anyways, thanks for the OSS work, I really appreciate your time. :heart: 💜

**Comment by remi** [comment]
Hi Paulo,

Thank you for your kind words!

We actually built our `ContentSecurityPolicy` module not to pass the `Config.CSP` security check but because we needed a way to build the content security policy based on runtime environment variables.

I think it could indeed be a great default for Phoenix but I don’t have time to right now to make that happen. But if you want to send a pull request to Phoenix with our module, please go ahead and do it. 😄 

Cheers!

**Comment by remi** [comment]
I’m going to close the issue. Let me know if you need anything else! ✌️

**Comment by gcauchon** [comment]
I asked myself the same question a few days ago while setuping a new project from the boilerplate.

Since the `sobelow` checks are based on the AST, `Config.CSP` only scans the Router module for en explicit use of the `:put_secure_browser_headers` plug WITH the a map containing the `"content-security-policy"` key. Implementing a more reliable check would mean recursively check every plugs and modules for the same key…

I doubt it would actually worth it! In the end after reading the documentation, it is up to you to disable the check if you feel like your code "comply" with the recommandation.
