### ISSUE TITLE
GitHub Actions Run make prepare step fails retrieving phoenix-framework

### ISSUE THREAD

**Issue by jasonsturges** [mirego/elixir-boilerplate#147]
GitHub Actions Run make prepare step fails while retrieving phoenix framework:

```
npm ci --prefix assets
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/phoenixframework/phoenix.git
npm ERR! 
npm ERR! Warning: Permanently added the RSA host key for IP address '140.82.114.4' to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-05-11T19_43_55_927Z-debug.log
make: *** [Makefile:62: prepare] Error 1
Error: Process completed with exit code 2.
```

Any recommendation for that, per how you use this boilerplate?

**Comment by gcauchon** [comment]
@jasonsturges It might be a momentary issue since the last runs in this very repository passed without errors… I also have multiple repositories forked from the boilerplate and they the `make prepare` target passed on every PR today!

- ✅ (4 hours ago) https://github.com/mirego/elixir-boilerplate/runs/2557462428?check_suite_focus=true#step:11:74
- ✅ (5 days ago) https://github.com/mirego/elixir-boilerplate/runs/2523356636?check_suite_focus=true#step:11:74

**Comment by jasonsturges** [comment]
@gcauchon Hi, thanks for the quick response and insight.

Strange, coming back to this project after a brief pause - this last run from 20-days ago also failed GitHub actions.

![image](https://user-images.githubusercontent.com/1213591/117878389-53140d80-b26b-11eb-80bd-0b28ef4b524a.png)

Locally my ssh is fine, wondering if there's something missed for GitHub Actions, though?

**Comment by gcauchon** [comment]
I forked my new projects (using LiveView, TailwindCSS and AlpineJS) out of this template, but made many upgrade since… Here are what my `mix.exs` and `package.json` files look like:

https://gist.github.com/gcauchon/1db4f96debade43f171804e39260c6d9

Note that I already upgrade to `Webpack 5` so all my NPM dependencies were up-to-date!

**Comment by gcauchon** [comment]
I also added my `.guthub/workflows/ci.yml` file in case this helps…

**Comment by jasonsturges** [comment]
@gcauchon Thanks for your time.
